### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by PEMapModder** [LegendOfMCPE/Oxidizer#1]
- Chat (Injections) API
  - [ ] Interface
  - [ ] Implementation
  - [ ] Implement for plugins
- Action (Prompt) API
  - [ ] Interface
  - [ ] Implementation
  - [ ] Implement for plugins
- Invisibility API
  - [ ] Interface
  - [ ] Implementation
  - [ ] Implement for plugins

**Comment by legoboy0215** [comment]
GOGO!

**Comment by legoboy0215** [comment]
Why only PEMapModder is doing this?

**Comment by PEMapModder** [comment]
@legoboy0215 good question
@LegendOfMCPE/members ^

**Comment by 64FF00** [comment]
@legoboy0215 @PEMapModder :'(

**Comment by legoboy0215** [comment]
I am quite excited for this actually...

**Comment by legoboy0215** [comment]
Is this dead? ...

**Comment by PEMapModder** [comment]
Well, I don't have time for this. @LegendOfMCPE/members someone work on this pls?

**Comment by legoboy0215** [comment]
^_^
